### ISSUE TITLE
Autoprefixer

### ISSUE THREAD

**Issue by Wolfr** [appuniversum/appuniversum#1]
Are we using autoprefixer at the moment?

**Comment by Dietr** [comment]
The gulp build process includes autoprefixer. In the ember components this is currently not the case. This is probably something we should define in our coding guidelines. Should we write prefixed SCSS or do we let the user determine how to handle prefixes? I prefer unprefixed but not quite sure if I followed this so far.

**Comment by Wolfr** [comment]
I like automated prefixing because it's one less thing to keep track of when writing CSS.
