### ISSUE TITLE
Monorepo proposal

### ISSUE THREAD

**Issue by Wolfr** [appuniversum/appuniversum#10]
Hi,

I reviewed some code and eventually I tried making a PR fixing a comment, here are my thoughts.

I think you're going to want to think about doing a monorepo (monolithic repo) where the documentation and the package live in the same repo; or many people are going to have workflow problems.

I've had to juggle two repo's with `npm link`, it's not fun from a workflow standpoint to change something in one project, to then have to save another project to see the result. If it's not fun for me I can see it not being fun for someone else.

What you want is to change the CSS and to see the documentation change with it. Your documentation = your unit test whether everything is working.

The branching on appuniversum.github.io feels weird, with `master` referring to the deploy, then `build` being the branch to work on (I guess this is Github pages related).

What I was fixing in the docs (the editor vs. content issue) was actually an issue from another repo. 

What we are going to want there is something that people know like git-flow.

We're also going to need a way to name branches to know which issue to refer to.

So, here's my proposal:

* Merge the appuniversum/appuniversum and appuniversum/appuniversium.github.io to one repository
* Work with git-flow: master is the reference version, development is what in development, use branches like `enhancement/xyz` or `feature/xyz` to have some organisation
* Keep working with 11ty for documentation purposes
* Deploy the site: not sure if we can use Github pages with a different repo structure?

What do you think?

**Comment by Dietr** [comment]
I agree, in practice it indeed seems a bit overkill to have this as seperate branches.

I merged the documentation to this repo.
- builds automatically from the master branch to gh-pages
- new url: https://appuniversum.github.io/appuniversum/

If all is good I'll remove the appuniversum.github.io branch.
