### ISSUE TITLE
Better separation between documentation CSS and appuniversum CSS

### ISSUE THREAD

**Issue by Wolfr** [appuniversum/appuniversum#13]
I think we need to put generic components in Appuniversum.

https://github.com/appuniversum/appuniversum/tree/master/documentation/assets/_scss/_components

Now some of them live in the documentation SCSS.

**Comment by Dietr** [comment]
I agree. This is some code that's deprecated since I started the ember-appuniversum repo.
For now I suggest to remove them and see if we can easily port the ember-appuniversum components to this repo.
