### ISSUE TITLE
Design tokens

### ISSUE THREAD

**Issue by Dietr** [appuniversum/appuniversum#14]
I did a test with using [theo](https://github.com/salesforce-ux/theo) to generate `scss` variables and a part of the documentation.

You can view the test on https://github.com/appuniversum/appuniversum/tree/feature/design-tokens

Is this something to go forward with or is it too complex for what we're doing? Any thoughts?

**Comment by Wolfr** [comment]
How do you like it yourself? Little bit afraid of overengineering here.

**Comment by Wolfr** [comment]
Would be interested to just have a file that we can agree on that looks a bit like this (warning, fictional values)

```
spacing
  - large: 5rem
  - medium: 2.5rem
  - small: 1rem
font-scale
  - 1: 4.8rem
  - 2: 3.6rem
  - 3: 2.8rem
colors
  - gray
    - 100: #[hex code]
    - 200: #[hex code]
```

**Comment by Dietr** [comment]
So far I like it but don't have a lot of experience with design tokens so still learning. This is low priority.

Pro's:
- possibility to sync with Webuniversum in the future?
- option to add meaning and comments (e.g. contrast colors) to a variable in a semantic way
- reuse of variables for automatic documentation generation in 11ty (e.g. colors)
- maybe some integration possible with Figma?
- I don't see a lot of overhead or maintenance for the moment (but that could change)
- extensible to iOS, Android, etc. (although this need does not exist for the moment)

Con's:
- steeper learning curve for people learning to use appuniversum
- not sure of the need of above benefits

I already started on completing the color variables: https://github.com/appuniversum/appuniversum/blob/feature/design-tokens/design-tokens/helpers/color-aliases.json

**Comment by Dietr** [comment]
Abandoned the design tokens for now but reworked the scss variable names in #31

**Comment by Wolfr** [comment]
Great <3
