### ISSUE TITLE
Some notes to discuss 

### ISSUE THREAD

**Issue by Wolfr** [appuniversum/appuniversum#15]
Some notes I made when implementing a site with appuniversum CSS

* Changed _d-content to _c-content: this is not documentation specific and can be a general component
* Changed _c-header to _c-main-header (as not to clash with new component .c-heading)
* Heading
  * Added _c-heading as a way to directly style a heading without creating div-itis
  * There is already a utility class u-headings, but then you have to remember to define the right font weight? Will lead to inconsistencies for sure
  * Proposal: remove `.u-headings` utility and create `.c-heading` component that has classes like `c-heading--1,` `c-heading--2`

Discussion to be had, or if it's clear from the above, opinions wanted.

**Comment by Dietr** [comment]
I agree on the `_c-content` and `_c-main-header` change.

Some thoughts on the other points:
- `_c-heading`: I like to define title styles in their respective component so it's clear where this heading style is used/defined. There is a risk of writing duplicate code but a general heading component seems hard to maintain across projects in my experience.
- I think the utility class could be useful for prototyping and the current refactoring state of our projects but not sure if we'll actually need it in the future. I would like to postpone this decission until we have created more components.

**Comment by Wolfr** [comment]
OK! Good to be clear on some of the things, and agree on postponing some discussions because they relate to coding style/habits/etc.

**Comment by Wolfr** [comment]
FWIW, the code style I like to use. I also use this snippet to explain the difference.

```
<!-- Do use c-heading-2 here to instantiate a certain typographic style -->
<h2 class="c-heading-2">My title</h2>
<div class="c-some-complex-component">
  <!-- Some complex code -->
</div>

<!-- Don't write long content that consists of multiple blocks with separate classes -->
<h2 class="c-heading-2">Hello world</h2>
<p class="c-body-1">My content</p>
<p class="c-body-1">My content</p>
<blockquote class="c-blockquote">My quote</blockquote>
<p class="c-body-1">My content</p>

<!-- Do wrap long content or the places where there is a possibility of long content (e.g. due to a CMS) in a class -->
<div class="c-content">
  <h2>Hello world</h2>
  <p>My content</p>
  <p>My content</p>
  <p>My content</p>
</div>
```

You would use `.c-heading--2` to get the equivalent of what is defined in the styles.

![image](https://user-images.githubusercontent.com/12690/77344901-25e96080-6d34-11ea-9dcc-a2770899d09a.png)

Whereas in your logic you would need multiple utility CSS classes to be consistent with the design.
