### ISSUE TITLE
Popover vs. dropdown

### ISSUE THREAD

**Issue by Wolfr** [appuniversum/appuniversum#17]
A discussion came up about popover vs dropdown, currently the [documented popover](https://appuniversum.github.io/ember-appuniversum/docs/components/au-popover) looks a bit like a dropdown to Johan (myself :)) 

Clarity to be found between team members.

**Comment by Dietr** [comment]
Dropdown is ok. Popover was the old name in our applications but not used extensively so it's not a big change to make.

**Comment by Wolfr** [comment]
![image](https://user-images.githubusercontent.com/12690/77425637-52a08500-6dd3-11ea-888c-eee8be0f482d.png)

It came up in a call with @mietcls that there might be some semantic confusion sometimes. I had made this comparison before about how different frameworks call things differently. It is unfinished.

Because we are merging codebases, we will have problems in understanding each other, because different terms mean different things to different people.

**Comment by Dietr** [comment]
To go forward, can we create an index page in the documentation to define some naming? I guess it will be easier if we have a reference before we create new components.

**Comment by Wolfr** [comment]
What about giving your naming disagreements to our current system? ([Figma link](https://www.figma.com/file/8tKG5CYiDDFPWJJ62kPYTj/AppUniversum-Master-Library?node-id=0%3A1))

**Comment by Dietr** [comment]
I'm ok with the naming you suggest. I also like an overview of component names (already created and future components). Maybe something like [this](https://bbc.github.io/gel/) in the documentation can provide a good guideline to move forward?

**Comment by Wolfr** [comment]
I'm 100% for having an overview of what is already created, and working towards a common goal.

But for short-term doability purposes, we could work with screenshots/layers in a figma file like we did for the colors.

Do note that we already put the components that were too specific in another library. We can sync between the specific components on your end and on our end and look at the differences then.
