### ISSUE TITLE
Container component

### ISSUE THREAD

**Issue by Wolfr** [appuniversum/appuniversum#19]
```
/* ==================================
   #CONTAINER
   ================================== */

/* Variables
   ========================================================================== */

$au-container-height: calc(100vh - #{$au-unit-large - $au-unit-tiny}) !default;

/* Component
   ========================================================================== */

.au-c-container {
  height: $au-container-height;
  overflow: hidden;
  position: relative;
}

.au-c-container__content {
  position: relative;
  height: $au-container-height;
  overflow: auto;
}
```

I am used to .container being the way to limit the width of something such as in Bootstrap.

What is the purpose of this code?

If it's a vertical container, perhaps it can be named as such?

Edit: it is probably the main container, maybe it can then be named "main-container".

(This also seems quite specific to the documentation layout)

**Comment by Dietr** [comment]
"main-container" seems fine to me. I'll adjust it.
We also use this in our main application dashboard to contain the height and scroll of our main content.
