### ISSUE TITLE
Publishing to CDN

### ISSUE THREAD

**Issue by Wolfr** [appuniversum/appuniversum#2]
To investigate: publishing to CDN. So appuniversum.css is easily usable in something like a CodePen. Any npm package is automatically available at https://unpkg.com/ .

**Comment by Dietr** [comment]
This repo is published on NPM: https://www.npmjs.com/package/@appuniversum/appuniversum

**Comment by Wolfr** [comment]
Great! So, what about referencing the generated CSS in something like a Codepen? I imagine that still has to be done? If I know it's a todo, we can send a PR.

**Comment by Dietr** [comment]
Yes, good idea.

**Comment by Dietr** [comment]
Can I close this issue or is there still something to be done here?

**Comment by Wolfr** [comment]
The initial question is not solved yet.

I can't figure out if it's really published or not.

Is this the current URL? https://unpkg.com/@appuniversum/appuniversum@0.0.5/appuniversum.css

I don't have publishing rights.

**Comment by Dietr** [comment]
The SCSS file seems to work:
https://unpkg.com/@appuniversum/appuniversum@0.0.5/appuniversum.scss

The CSS does not seem to be included for now. I'm not sure how to fix that.

**Comment by Wolfr** [comment]
https://github.com/appuniversum/appuniversum/blob/master/.npmignore and https://github.com/appuniversum/appuniversum/blob/master/.gitignore seem to be set up correctly.

Are we sure we generate the CSS on the initial `gulp` command? Or only on save? When publishing with `npm publish .` the file needs to exist.

The [“prepare” command in package.json](https://github.com/appuniversum/appuniversum/blob/master/package.json#L13) is executed right before sending it to npm .

It's hard for me to debug from a distance, if you can assign my npm account `wolfr` to have publishing rights I can help.

**Comment by Dietr** [comment]
@Wolfr CSS is now available on: https://unpkg.com/@appuniversum/appuniversum@0.0.6/appuniversum.css

**Comment by Wolfr** [comment]
Just a note, I think it would be useful in this development phase if it was not minified.
