### ISSUE TITLE
$au-rotation

### ISSUE THREAD

**Issue by Wolfr** [appuniversum/appuniversum#20]
<img width="307" alt="Screenshot 2020-03-24 at 13 24 22" src="https://user-images.githubusercontent.com/12690/77425292-cdb56b80-6dd2-11ea-99cb-26b23cebc3ab.png">

What is this used for?

**Comment by Dietr** [comment]
This is used in the header as the angled divider next to the "Vlaanderen" icon. This probably shouldn't be a generic variable like it is now but in the moment I thought it could be useful in the future to create consistent angles.

**Comment by Wolfr** [comment]
OK! Probably best to make this specific to the component in my opinion, this tripped me over enough to make an issue.
