### ISSUE TITLE
Icon font vs SVG icons

### ISSUE THREAD

**Issue by Wolfr** [appuniversum/appuniversum#3]
Technical discussion to be had about which solution to go for, as well as which icons we want.

**Comment by Dietr** [comment]
I personally prefer SVG-icons (as a symbolset) for ease of use and A11Y reasons. But I see practical advantages to an icon-font (for use in Ember). Is there any possibility to provide both options? Or will this bring too much overhead?

**Comment by Wolfr** [comment]
I have never used the Symbolset technique, how do you generate it?

I also see the current code references a few icons that are specific to your needs in your project (mandaten etc.). I guess the first question is: which icons do we document?

Here is a screenshot of our current icons in our project. 

* 32 24x24 icons
* 7 18x18 icons

![image](https://user-images.githubusercontent.com/12690/76873922-b6283100-686e-11ea-9e89-1ce8d593388f.png)

**Comment by Dietr** [comment]
I have used https://github.com/Hiswe/gulp-svg-symbols to generate a symbolset from a folder of seperate icons. 
```js
// Example gulp function
function icons() {
  return gulp.src(project.iconSrc)
    .pipe(cheerio({
      run: function ($) {
        $('[fill]').removeAttr('fill');
      },
      parserOptions: { xmlMode: true }
    }))
    .pipe(svgSymbols({
      title: '%f icon',
      svgAttrs: {
        class: 'c-icon-set',
      },
      templates: ['default-svg']
    }))
    .pipe(gulp.dest(project.buildDest + project.iconDest))
    .pipe(browsersync.stream());
}
```
The symbolset is used in the following way
```html
<svg role="img" class="c-icon c-icon--{{ value }}">
  <use xlink:href="/assets/img/svg/svg-symbols.svg#{{ value }}"></use>
</svg>
```

We do have different project specific icons so it does not seem necessary to include all possible icons here. Therefore the main question for me is how we can easily add icons in our own project within the Appuniversum CSS/Components. How would you do that with an iconfont?

A suggestion to provide a basic set:
- link/button icons (e.g. arrow, back arrow, help, manual, ...)
- close icon (e.g. for a modal)
- status icons (e.g. info, alert, warning, locked, open, hidden, editable, ...)
- other generic ui icons (e.g. dropdown arrow, )

**Comment by Wolfr** [comment]
Our workflow uses https://www.npmjs.com/package/icon-font-generator to generate an icon font based on a folder of SVGs. We have a separate repo demo that uses this that we can share.

Your workflow uses a gulp task to generate an SVG based on a folder of SVGs.

Then there is also direct inlining of SVGs - that's another workflow.

Every method has its disadvantages and benefits. Since icons occur in buttons and in UI elements and this also requires specific CSS I think we need to agree on a common thing.

I can conform to your style of working with `<use>` but I have never used (haha) this. So I don't know which pitfalls this method has, questions that come to mind are:

* What about browser support of this method?
* What about multi color icons?
* What about Id clashing? What is multiple icons have the same id or class references? Does this cause problems in practice?
* What about stylability/colorability through CSS? Can we color with code such as `path * { fill: #ff0000 }` when using SVGs through `use`?

I am definitely going to read up on this!

**Comment by mietcls** [comment]
Sidenote: we currently support Firefox, Safari and Chrome.

Do we take the official icons into account? They might not be good enough for apps though. https://overheid.vlaanderen.be/communicatie/huisstijl/huisstijl-iconen

**Comment by Wolfr** [comment]
We have no defined browser support. I am pretty sure the app is largely untested in Safari.

**Comment by Dietr** [comment]
I did a test in ember-appuniversum (https://github.com/appuniversum/ember-appuniversum/tree/feature/icons-test). Building an svg symbolset from multiple locations is possible in with [this plugin](https://github.com/BrianSipple/ember-cli-svgstore) so we could have a generic set in appuniversum and add our own custom icons in our project. 

I'm looking into a similar test with iconfonts to help move this decision forward.

To answer your questions:
- Svg use is supported in Edge, Firefox, Chrome and Safari. We will need to test our implementation to make sure everything works as intended.
- Multi color icons is possible when you add id's to your original SVG icon's paths
- Id clashing is a possiblity if we build icons from various sources. I suggest we namespace the appuniversum icons and our project icons. The id is derived from the filename so id clashing is impossible if you're building from a single folder.
- Styling can be done by using fill or stroke. See [this example](https://github.com/appuniversum/appuniversum/blob/master/documentation/assets/_scss/_components/_c-icon.scss)

**Comment by Wolfr** [comment]
Our current testing project (the manual) does not use Ember, but it's in 11ty, so we would like the solution to be independent from Ember.

We could do a test using the gulp workflow + symbolset and add it to our project as a separate addition.

**Comment by Dietr** [comment]
Ok, I can add a gulp function here so we can continue the testing.
For ember I had no luck yet implementing the icon-font solution. Any ideas on your end on how to do this?

**Comment by Wolfr** [comment]
I would recommend adding the icon-font as a separate package.

Example: https://github.com/appuniversum/appuniversum-icon-font 

I cannot publish to npm, I'll ask for help in the chat.

**Comment by mietcls** [comment]
We will pick this up later – we do not use enough icons to have this discussion right now and will work with it practically in ember.

**Comment by Wolfr** [comment]
OK, we do have to implement something with icons today, but we will do it in whatever way looks most productive to us now and then later have this discussion.

**Comment by Wolfr** [comment]
<img width="1276" alt="Screenshot 2020-04-10 at 09 00 14" src="https://user-images.githubusercontent.com/12690/78970493-b9c77480-7b09-11ea-81bc-740ed7416693.png">

@Dietr I saw that these icons are documented now, but where are the source files kept?

**Comment by Dietr** [comment]
The icon source files are kept in [/public/icons/](https://github.com/appuniversum/ember-appuniversum/tree/master/public/icons). If necessary I can also put them in the shared Figma file.
