### ISSUE TITLE
Utilities for word break

### ISSUE THREAD

**Issue by Dietr** [appuniversum/appuniversum#38]
Add utilities for:
- white-space: nowrap
- word-break: break-word

**Comment by Windvis** [comment]
It seems this was recently added with [this commit](https://github.com/appuniversum/appuniversum/commit/29ce8e9f2d508b156dfa7f0960a13d896c34e419) by @mietcls!

**Comment by mietcls** [comment]
Yes @Windvis first basic version added, we probably need to look through our naming system (I see some inconsistencies in naming, I now made it similar to text-align but it probably needs more thinking). Closing for now!
