### ISSUE TITLE
Indent for BEM children?

### ISSUE THREAD

**Issue by Wolfr** [appuniversum/appuniversum#4]
I don't see the need to indent BEM children 1 tab level.

I would like this not to be the case.

Any thoughts @Dietr ? Is this something you have maybe been doing for a long time? I've never done this, and I think it it unnecessary.

Example: L29-110 in https://github.com/appuniversum/appuniversum.github.io/blob/build/documentation/assets/_scss/_appuniversum/_c-brand.scss#L29-L110

We could also get an opinion from Rafaël.

**Comment by Dietr** [comment]
It's a habit and in my opinion it provides a clear visual distinction from the main BEM component.
I have no problems with changing this as it's purely a visual preference.

**Comment by Wolfr** [comment]
I am against it, but I can deal with it, I just want a project-level agreement and then I will conform to whatever we decide. Maybe @rafael-mindreau can help us out with his opinion. 

(I wanted to have it raised in the beginning of the project though)

**Comment by rafael-mindreau** [comment]
I wouldn't have thought of doing this. My editor would also auto-fix that indentation there in some cases. I would have bent my head around why the indentation was done like that without the context of this discussion. I can however see why it's been used. I wouldn't recommend doing this. It caused some confusion on my side, as I'm not super CSS-savvy 😅

**Comment by Wolfr** [comment]
Good point about auto-fixing from some IDEs.
