### ISSUE TITLE
Outlines

### ISSUE THREAD

**Issue by Wolfr** [appuniversum/appuniversum#5]
```
// Only show outlines to keyboard users
:focus:not(:focus-visible),
button:focus:not(:focus-visible) {
  outline: none
}
```

Not sure about this code. I don't think it's wise to reset this, the browser support of this also seems limited. I would just leave outlines alone to be honest, for accessibility reasons.

Also, I do see a visible outline in the documentation. So I am a bit confused here.

![image](https://user-images.githubusercontent.com/12690/76858254-53776b00-6857-11ea-95c3-f80ea97834b5.png)

**Comment by Dietr** [comment]
I agree. This is currently not working. Let's remove this.
