### ISSUE TITLE
Feedback on `_d-editor` component

### ISSUE THREAD

**Issue by Wolfr** [appuniversum/appuniversum#6]
The `_d-editor` components could use a better name in my opionion.

I don't know if a general public will recognize the usage of this component with the current name.

In Mono projects this component is typically named `.e-cms` (referring to content from a CMS) or `.c-content`.

In WU3, you instantiate typographic styles with `vl-typography`.

Code reference: https://github.com/appuniversum/appuniversum.github.io/blob/build/documentation/assets/_scss/_documentation/_d-editor.scss

**Comment by Dietr** [comment]
I agree. I prefer `au-d-content` as it feels more descriptive of what the component's function is. `au-d-typography` feels a bit generic to me.
