### ISSUE TITLE
Side navigation 

### ISSUE THREAD

**Issue by Wolfr** [appuniversum/appuniversum#8]
In the side navigation of the docs, an underline is used.

<img width="210" alt="Screenshot 2020-03-17 at 16 34 41" src="https://user-images.githubusercontent.com/12690/76872876-4d8c8480-686d-11ea-967e-81fc4bcea521.png">

Here is a design of a sidebar in our app

![image](https://user-images.githubusercontent.com/12690/76872938-6301ae80-686d-11ea-8b07-b99f22091818.png)

We typically do not user underlines in navigation bars.

My preference would be to have those underlines removed.

Any opinions?

**Comment by Dietr** [comment]
I think there should be a clear visual indication that a sidebar item is clickable as there are also section titles and other non-clickable items present. We used an underline but this could also be an icon or some other indication. A hover state does not seem sufficiant to me.
